import './globals.css'

import type { Metadata } from 'next'
import { Space_Grotesk } from 'next/font/google'
import localFont from 'next/font/local'
import { Toaster } from 'sonner'

import { ThemeProvider } from '@/components/theme-provider'

import { CourseProvider } from './contexts/course'

const poppins = localFont({
  src: [
    {
      path: './fonts/poppins/Poppins-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/poppins/Poppins-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/poppins/Poppins-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/poppins/Poppins-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-poppins',
})

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-space-grotesk',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <ThemeProvider
        attribute="class"
        defaultTheme="light"
        enableSystem
        disableTransitionOnChange
      >
        <CourseProvider>
          <body
            className={`${poppins.variable} ${spaceGrotesk.variable} antialiased font-sans bg-background h-screen`}
          >
            <main className="flex flex-col items-center justify-start size-full">
              {children}
            </main>
            <Toaster
              toastOptions={{
                className:
                  'bg-card rounded-md text-card-foreground border-input',
              }}
            />
          </body>
        </CourseProvider>
      </ThemeProvider>
    </html>
  )
}
